services:
  postgres-dev:
    image: postgres:latest
    environment:
      POSTGRES_USER: open_voices
      POSTGRES_PASSWORD: open_voices
      POSTGRES_DB: open_voices
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local